name: Integration
description: "Integration workflow"

on:
  push:
    branches:
      - main
      - development
      -  feature/*
      -  bugfix/*
      -  hotfix/*
      -  release/*
  pull_request:
    branches:
      - main
      - development
      -  feature/*
      -  bugfix/*
      -  hotfix/*
      -  release/*

jobs:
  ci-checks:
    name: CI Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run CI Checks
        id: ci-checks
        uses: ./.github/actions/ci-checks

      - name: Check project versioning
        id: check_versioning
        run: |
          echo "Checking project versioning..."
          PROJECT_VERSION=$(cat ./src/__init__.py | grep -oP '(?<=__version__ = ")[^"]*')
          git fetch --tags --unshallow || git fetch --tags
          LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null || echo "")
          if [ -z "$LATEST_TAG" ]; then
            echo "No git tags found. Please create a tag before running this workflow."
            exit 1
          fi
          echo "project_version=$PROJECT_VERSION" >> $GITHUB_OUTPUT
          echo "latest_tag=$LATEST_TAG" >> $GITHUB_OUTPUT
          if [[ $PROJECT_VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+$ && $PROJECT_VERSION > $LATEST_TAG ]]; then
            exit 0
          else
            echo "Please update the project version. Current version: $PROJECT_VERSION, Latest tag: $LATEST_TAG"
            exit 1
          fi

      - name: Workflow resume
        run: |
          REPO_URL="https://github.com/${{ github.repository }}"
          TAG_URL="$REPO_URL/releases/tag/${{ steps.check_versioning.outputs.latest_tag }}"
          echo "## ðŸŽ‰ Workflow Execution Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| ðŸ·ï¸ Latest Git Tag | ðŸ“¦ Project Version |" >> $GITHUB_STEP_SUMMARY
          echo "|:-----------------:|:------------------:|" >> $GITHUB_STEP_SUMMARY
          echo "| [${{ steps.check_versioning.outputs.latest_tag }}]($TAG_URL) | ${{ steps.check_versioning.outputs.project_version }} |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          if [ "${{ steps.check_versioning.outputs.project_version }}" = "${{ steps.check_versioning.outputs.latest_tag }}" ]; then
            echo "âœ… **Versions match!**" >> $GITHUB_STEP_SUMMARY
            else
            echo "Attention: ðŸš¨ **Versions do not match!**" >> $GITHUB_STEP_SUMMARY
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
